//
// Created by vbrau on 8/11/2018.
//

#ifndef LD42_DEFS_H
#define LD42_DEFS_H


#define GRID_ROWS 5
#define GRID_COLS 7

#define STEEL_FOR_NEW_ROW 30
#define STEEL_REFINERY_POWER 3
#define STEEL_REFINERY_STEEL_COST 5
#define STEEL_RATE 3

#define WIND_POWER_GEN 10
#define WIND_STEEL_COST 4

#define MINE_RATE 5
#define MINE_POWER 5
#define MINE_STEEL_COST 10

#define MIN_STORE_STEEL_COST 2
#define MIN_STORE_AMOUNT 30

#define FUEL_STORE_POWER 0
#define FUEL_STORE_STEEL_COST 3
#define FUEL_STORE_AMOUNT 15

#define FUEL_REFINERY_POWER 3
#define FUEL_REFINERY_STEEL_COST 6
#define FUEL_REFINERY_RATE 2

#endif //LD42_DEFS_H
